name: Docker Image CI

on:
  workflow_run:
    workflows: [ "Build and test" ]     
    types:
      - completed

jobs:
  push-to-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/syncspace:latest .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/syncspace:latest
